- hosts: localhost
  tasks:

  - name: create a new ec2 key pair, returns generated private key
    amazon.aws.ec2_key:
      name: my_keypair
    register: my_keypair

  - debug:
      var: my_keypair

  - name: remove key pair by name
    amazon.aws.ec2_key:
      name: my_keypair
      state: absent
